export const images = {
  logo: require('./../assets/images/logo.svg'),
  mainvideo: require('./../assets/images/mainvideo.mp4'),
  BuildingImg1: require('./../assets/images/buildingImg1.png'),
  BuildingImg2: require('./../assets/images/buildingImg2.png'),
  BuildingImg3: require('./../assets/images/buildingImg3.png'),
  BuildingImg4: require('./../assets/images/buildingImg4.png'),
  BuildingImg5: require('./../assets/images/buildingImg5.png'),
  BuildingImg6: require('./../assets/images/buildingImg6.png'),
  map: require('./../assets/images/mapimg.png'),
  TeamImg1: require('./../assets/images/teamimg.png'),
  DetailBannerimg: require('../assets/images/detailbanner1.png'),
  Detailbannerelementimg1: require('../assets/images/Detailbannerelementimg1.png'),
  MediaBannerimg: require('../assets/images/mediabannerimg.png'),
  Teambannerimg: require('../assets/images/teambannerimg.png'),
  ContactUsbanner1: require('../assets/images/ContactUs1.png'),
  Locationbanner1: require('../assets/images/Locationbanner1.png'),
  LocationCard1: require('../assets/images/LocationCard1.png'),
  LocationCard2: require('../assets/images/LocationCard2.png'),
  LocationCard3: require('../assets/images/LocationCard3.png'),
  LocationCard4: require('../assets/images/LocationCard4.png'),
  LocationCard5: require('../assets/images/LocationCard5.png'),
  Locationimgbox1: require('../assets/images/Locationimgbox1.png'),
  Arrow_leftside: require('../assets/images/Arrow_leftside.png'),
  Arrow_rightside: require('../assets/images/Arrow_rightside.png'),
  locationlogo: require('./../assets/images/locationLogo.png'),
  Availabilitybanner: require('../assets/images/Availabilitybanner.png'),
  Availabilitysidecard: require('../assets/images/Availabilityside card.png'),
  Availabilityplan1: require('../assets/images/Acailabilityplan1.png'),
  IntheNewa1: require('../assets/images/IntheNewa1.png'),
  AwardImg1: require('../assets/images/awardImg1.png'),
  AwardImg2: require('../assets/images/awardImg2.png'),
  AwardImg3: require('../assets/images/awardImg3.png'),
}
